/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_administrator_ndk_Native */

#ifndef _Included_com_example_administrator_ndk_Native
#define _Included_com_example_administrator_ndk_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_administrator_ndk_Native
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_administrator_ndk_Native_add__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_administrator_ndk_Native
 * Method:    add
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_administrator_ndk_Native_add__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_example_administrator_ndk_Native
 * Method:    add
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_example_administrator_ndk_Native_add___3B
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_example_administrator_ndk_Native
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_administrator_ndk_Native_sayHello
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_administrator_ndk_Native
 * Method:    getTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_example_administrator_ndk_Native_getTime
  (JNIEnv *, jobject);

/*
 * Class:     com_example_administrator_ndk_Native
 * Method:    accessField
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_administrator_ndk_Native_accessField
  (JNIEnv *, jobject);

/*
 * Class:     com_example_administrator_ndk_Native
 * Method:    getPerson
 * Signature: ()Lcom/example/administrator/ndk/Person;
 */
JNIEXPORT jobject JNICALL Java_com_example_administrator_ndk_Native_getPerson
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
